Value(B, Byte, byte, int8_t, Byte)
Value(D, Double, double, double, Double)
Value(F, Float, float, float, Float)
Value(I, Integer, int, int32_t, Int)
Value(J, Long, long, int64_t, Long)
Value(S, Short, short, int16_t, Short)
