name := PrivaCy
base := ../tweaks
flags := -framework UIKit -framework SpringBoardServices
include ../tweaks/tweak.mk

extra:
	mkdir -p package/Library/PreferenceLoader/Preferences
	cp -a Privacy.plist PrivacyIcon.png package/Library/PreferenceLoader/Preferences
