src/org/creativestudies/platinum/Session.class: src/org/creativestudies/platinum/Session.java
	@ant

test: src/org/creativestudies/platinum/Session.class
	@rm -rf dat*.html
	@java org.creativestudies.platinum.Session
